build:
  image: node:$$NODE_VERSION
  commands:
    - npm install
    - npm run lint
    - npm test
matrix:
  NODE_VERSION:
    - 0.10
    - 0.12
    - 4
    - 6
    - 7
notify:
  slack:
    webhook_url: $$SLACK_HOOK
    channel: alerts
    username: drone
